repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.219'
  hooks:
    - id: ruff
      args: ["--force-exclude", "--fix"]
