_target_: walkjump.archs.lms.LangevinManifoldSamplerConf
n_tokens: 21
chain_len: 297  # combined hc & lc
denoise_model: "s3://prescient-data-dev/sandbox/berenbed/walk-jump/models/2023-01-26T10-23-52/last.ckpt"
kernel_sizes: [15, 5, 3]
hidden: 32
friction: 1.0
activation: 'relu'
reg_l2_norm: 0.0
